import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
	"/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */" +
	"\n" +
	"if (typeof globalThis.__filename === 'undefined') globalThis.__filename = require('path').basename(__filename);" +
	"\n" +
	"if (typeof globalThis.__dirname === 'undefined') globalThis.__dirname = require('path').dirname(__filename);" +
	"\n" +
	"if (typeof globalThis.require === 'undefined') globalThis.require = require;";

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js"
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
